spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_HOST_PORT:3306}/${MYSQL_DATABASE:todaypoor}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${MYSQL_USER:todaypoor}
spring.datasource.password=${MYSQL_PASSWORD:todaypoor}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret-key=${JWT_SECRET}
jwt.access-expiration-time=${JWT_ACCESS_EXPIRATION:3600000}
jwt.refresh-expiration-time=${JWT_REFRESH_EXPIRATION:1209600000}

