spring.application.name=todaypoor-be

# JWT
jwt.secret.key=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION:3600000}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION:1209600000}

